### ISSUE TITLE
Preview stuck when drilling enabled

### ISSUE THREAD

**Issue by petrasl1976** [GridSpace/apps#10]
When i enable drilling preview stuck. I have created hols exact size as defined tool. When i disable drilling - preview is generated successfully

![image](https://user-images.githubusercontent.com/30649191/33442759-9b2cd5d6-d5fe-11e7-9a00-b76615654ffc.png)

**Comment by stewartoallen** [comment]
Is this still happening? Can you share the model and tool settings that are causing this problem?

**Comment by petrasl1976** [comment]
Here are the tool options. How can i share tha model? Could you provide your email please?
![image](https://user-images.githubusercontent.com/30649191/34512180-4ccd782a-f069-11e7-9290-954bbffd898e.png)

**Comment by stewartoallen** [comment]
sa@grid.space -- thanks

**Comment by stewartoallen** [comment]
The holes on the sides are 3.6mm, so creating a 3.6mm tool causes drilling to work properly.  Your tool is 3.175 which is less than the hole diameter, so drilling does not detect it.  I was unable to duplicate your problem with slicing getting stuck with drilling enabled.  Can you open the Javascript (developer) console and look for errors?

<img width="2560" alt="screen shot 2018-01-03 at 10 24 42 am" src="https://user-images.githubusercontent.com/554275/34526522-adc62490-f070-11e7-88db-6b4a63663989.png">

**Comment by petrasl1976** [comment]
Hi,

Strange. I cant reproduce this also. But it really stuck before (when i
posted this). Apologize for "fake alarm" :(

Regards

**Comment by stewartoallen** [comment]
no worries. just re-open the ticket if you can reproduce it.
