### ISSUE TITLE
Laser Cutter line colors

### ISSUE THREAD

**Issue by BurtHarris** [GridSpace/apps#11]
I've got access to a ULS laser cutter/engraver at the local tech school.   The way they have it set-up it expects red lines for vector cuts, blue lines for vector engraving, and any other color (or wide lines) is done with raster engraving.    

It seems that Kiri:Moto SVG output has blue lines hard coded, but it looks fairly simple to change this in a local repository, but I don't understand how I would go about testing it from OnShape.   Any guidance?

**Comment by BurtHarris** [comment]
Is there a reason blue line color is hard coded?   Should this be made into a setting?

**Comment by stewartoallen** [comment]
Agree it should be configurable.  Until such time, can you just use text replace on the generated SVG?

**Comment by BurtHarris** [comment]
I tried this and ran into an unrelated problem, Chrome for some reason renders even the narrowest lines wider then specified in the SVG when printing them, and that behavior interfere's with using SVG via Chrome to drive ULS's print driver.   It doesn't seem to be addressable with any change in the SVG itself...

Thank
