### ISSUE TITLE
Laser Cutting slice step fails in OnShape

### ISSUE THREAD

**Issue by sir-buckyball** [GridSpace/apps#12]
When slicing a part in OnShape using kiri:moto, instead of being successful as usual I consistently get an alert box which says "true".

I'm using a Chromebook Pixel 2 (always the up to date version of Chrome).

I _think_ this is in part due to https://github.com/GridSpace/apps/commit/c1fdd341f72acbf1ed2a730db6ba2410745f3d88 (where I've made a similar comment).

**Comment by stewartoallen** [comment]
I have a proper fix that I will check in later today. thanks for the report.
