### ISSUE TITLE
new error dialog

### ISSUE THREAD

**Issue by holla2040** [GridSpace/apps#13]
I'm getting a new error since the last time I ran moto (mid Jan 2018). see screenshot

![screenshot from 2018-02-05 19-54-35](https://user-images.githubusercontent.com/1024542/35839626-ab7f1194-0aae-11e8-8f84-79c8da184f11.png)

**Comment by stewartoallen** [comment]
sorry about that. just pushed an update that should remove the alert.

**Comment by stewartoallen** [comment]
re-open if this hasn't been solved.

**Comment by holla2040** [comment]
All good,  no dialog today.  Thanks,  closed ticket is fine
