### ISSUE TITLE
slice & preview fail when running locally

### ISSUE THREAD

**Issue by ajmirsky** [GridSpace/apps#2]
I selected CNC milling mode, imported an STL file, defined stock size. When slice or preview is clicked, the part turns red and the slicing progress bar shows up, but it doesn't seem to go anywhere. I tried on grid.space and the same sequence works.

Unfortunately, the console doesn't show any messages after clicking slice or preview (all the other information shows up prior).

OSX 10.11, node 7.10.0

The browser console shows a few messages, but occur before slice or preview is clicked. The node console doesn't show any message either.

Happy to help debug / fix if you could point me in the right direction of where to start looking.  I've also included the stl file (although the same thing happens with the default object that appears on when Kiri first loads.

Thanks!

![kiri moto slicing failure](https://cloud.githubusercontent.com/assets/323371/26164752/9b4c46c6-3afb-11e7-8230-3555f0219494.png)

[stepper mount.stl.txt](https://github.com/GridSpace/apps/files/1008429/stepper.mount.stl.txt)

**Comment by ajmirsky** [comment]
![kiri console](https://cloud.githubusercontent.com/assets/323371/26165036/98c6e6c6-3afc-11e7-8ee6-38e51d94c656.png)

**Comment by stewartoallen** [comment]
are you starting the server with

node js/web-server debug

are you connecting to localhost:8080/kiri ?

in order to debug web workers and get non-compressed / obfuscated code served to the browser, you need to do both of those things.

**Comment by ajmirsky** [comment]
i have tried `npm start` as well as `node js/web-server debug` and can get the site to load at localhost:8080/kiri with no problems. I'm able to import an STL file and manipulate its orientation, select the cnc milling mode and alter the settings. 

it's only when i go to and try to run the slice/preview functionality to generate the toolpath that I run into an issue.

I've included another screen which includes the browser frame which shows it loading from `localhsot:8080/kiri`.
![kirimoto](https://cloud.githubusercontent.com/assets/323371/26276989/1203334a-3d51-11e7-8697-7c974689d11f.png)

**Comment by stewartoallen** [comment]
You should be able to open the javascript debug console and get a line # now for the error

**Comment by uncencored** [comment]
I have a same problem with Slice function. Both of pi and linux Mint. 
![image](https://user-images.githubusercontent.com/22325354/32550693-a18e1e16-c4c0-11e7-9b87-1f6c66ec3211.png)

**Comment by stewartoallen** [comment]
are you using "npm start" to start the web server side?

**Comment by stewartoallen** [comment]
ok, i've replicated this running on a PI.  will let you know what I find.  thanks
