### ISSUE TITLE
Need better controls for moving objects on bed

### ISSUE THREAD

**Issue by biscuitlad** [GridSpace/apps#3]
Hi

I have an object that needs precise rotating and positioning (in terms of vertical height) in order to generate the correct supports. I can't do it with the keyboard controls, the granularity (5 degrees / 5 mm) is much too coarse. My model is left either floating in the air or it loses the first 2 mm, or it generates supports where none are needed if the rotation is correct.

Can you provide keyboard shortcuts that work on a laptop / chromebook? [option-arrow-down]	move object(s) down 5mm  - option? What key is that? Doesn't exist on my Chromebook pixel!

What can I do to move the object? There don't seem to be any mouse controls that do the same as the arrow keys for positioning the object.

**Comment by stewartoallen** [comment]
I have added a new feature (version 1.0.62) and pushed it to the live site.  Use Shift-R to bring up a dialog that will allow you to enter x,y,z arbitrary rotations for the selected objects.  Otherwise, Shift-ArrowKey should rotate the object 5 degress on X or Z.
