### ISSUE TITLE
Laser Cut Outlines Overlap

### ISSUE THREAD

**Issue by Miserlou** [GridSpace/apps#8]
First of all - THANK YOU! This project is just what I needed, so cool.

Currently exporting the default object as SVG causes overlap of the arranged slices, like so (look at the left):

<img width="1149" alt="screen shot 2017-10-31 at 11 11 15 pm" src="https://user-images.githubusercontent.com/139987/32258456-f036bcc0-be90-11e7-96e2-5f4aba7f3c88.png">

This isn't really a problem because you can move them around in Inkscape or whatever, but it'd be nice if this just didn't overlap the layers - even better, if you could supply a ratio/bed size and fill to that to minimize sheets needed!

**Comment by Miserlou** [comment]
This problem seems to happen mostly with the small bits.

<img width="450" alt="screen shot 2017-10-31 at 11 23 19 pm" src="https://user-images.githubusercontent.com/139987/32258716-8e6449a2-be92-11e7-9d21-09d92be161ac.png">

**Comment by Miserlou** [comment]
You've really done a super job with this software, I'm very impressed.

**Comment by stewartoallen** [comment]
thanks! this shouldn't be too hard to fix.

**Comment by stewartoallen** [comment]
found and fixed.  please let me know if it works for you.  you will have to reload the page. hovering your mouse over the "help" button should reveal a version of "1.0.67" or greater.  if not, you're getting a cached/old copy.

**Comment by Miserlou** [comment]
Wow, that was fast! You are awesome!
