### ISSUE TITLE
Tool plunge issue while cutting plywood

### ISSUE THREAD

**Issue by petrasl1976** [GridSpace/apps#9]
Hi,
While cutting playwood with single pass (lets say simple square with hole inside) tool plunging not directly down, but gradually while cutting the first front edge. The same while cutting holes. I set "step down" to 6mm, same thicknes as my playwood and enabled waterline" and "origin top". As per my understanding tool should go straight down and only then cut the first edge (see green arrows in screeshot), instead it plunging gradually (red arrows in screenshot).

Thank you! And let me know if i can do or perform some testing for you.

![image](https://user-images.githubusercontent.com/30649191/33242086-f2c9295e-d2d7-11e7-9176-518f211faefd.png)

and gcode below exported by kiri:moto:

G21
G90
M3 S16000
M6 T2
G0 X-1.5875 Y-1.5875 Z3.0
G1 X151.5875 Z-6.0 F400
G1 Y75.5193
G1 X161.5875 Y90.5193
G1 Y171.4807
G1 X151.5875 Y186.4807
G1 Y263.5875
G1 X-1.5875
G1 Y185.5106
G1 X8.6329 Y170.5106
G1 Y91.4894
G1 X-1.5875 Y76.4894
G1 Y-1.5875
G0 Z3.0
G0 X31.1875 Y6.4875
G1 X38.8125 Z-6.0
G1 Y9.4125
G1 X31.1875
G1 Y6.4875
G0 Z3.0
G0 X61.1875
G1 X88.8125 Z-6.0
G1 Y9.4125
G1 X61.1875
G1 Y6.4875
G0 Z3.0
G0 X121.1875
G1 X128.8125 Z-6.0
G1 Y9.4125
G1 X121.1875
G1 Y6.4875
G0 Z3.0
G0 X133.6855 Y87.654
G1 X135.0 Y87.5894 Z-6.0
G1 X136.3145 Y87.654
G1 X137.6163 Y87.8471
G1 X138.8929 Y88.1669
G1 X140.132 Y88.6103
G1 X141.3217 Y89.1729
G1 X142.4505 Y89.8495
G1 X143.5076 Y90.6335
G1 X144.4827 Y91.5173
G1 X145.3665 Y92.4924
G1 X146.1505 Y93.5495
G1 X146.8271 Y94.6783
G1 X147.3897 Y95.868
G1 X147.8331 Y97.1072
G1 X148.1529 Y98.3837
G1 X148.346 Y99.6856
G1 X148.4125 Y101.0391
G1 Y160.9609
G1 X148.346 Y162.3144
G1 X148.1529 Y163.6163
G1 X147.8331 Y164.8928
G1 X147.3897 Y166.132
G1 X146.8271 Y167.3217
G1 X146.1505 Y168.4505
G1 X145.3665 Y169.5076
G1 X144.4827 Y170.4827
G1 X143.5076 Y171.3665
G1 X142.4505 Y172.1505
G1 X141.3217 Y172.8271
G1 X140.132 Y173.3897
G1 X138.8929 Y173.8331
G1 X137.6163 Y174.1529
G1 X136.3145 Y174.346
G1 X135.0 Y174.4106
G1 X133.6855 Y174.346
G1 X132.3836 Y174.1529
G1 X131.1071 Y173.8332
G1 X129.8679 Y173.3897
G1 X128.6783 Y172.8271
G1 X127.5495 Y172.1505
G1 X126.4924 Y171.3665
G1 X125.5173 Y170.4827
G1 X124.6335 Y169.5076
G1 X123.8495 Y168.4505
G1 X123.1729 Y167.3217
G1 X122.6102 Y166.132
G1 X122.1669 Y164.8929
G1 X121.8471 Y163.6163
G1 X121.654 Y162.3144
G1 X121.5875 Y160.961
G1 Y101.0391
G1 X121.654 Y99.6856
G1 X121.8471 Y98.3837
G1 X122.1669 Y97.1071
G1 X122.6102 Y95.868
G1 X123.1729 Y94.6783
G1 X123.8495 Y93.5495
G1 X124.6335 Y92.4924
G1 X125.5173 Y91.5173
G1 X126.4924 Y90.6335
G1 X127.5495 Y89.8495
G1 X128.6783 Y89.1729
G1 X129.8679 Y88.6103
G1 X131.1071 Y88.1669
G1 X132.3836 Y87.8471
G1 X133.6855 Y87.654
G0 Z3.0
G0 X24.4125 Y94.8125
G1 X21.5875 Z-6.0
G1 Y67.1875
G1 X24.4125
G1 Y94.8125
G0 Z3.0
G0 Y167.1875
G1 Y194.8125 Z-6.0
G1 X21.4875
G1 Y167.1875
G1 X24.4125
G0 Z3.0
G0 X31.1875 Y252.5875
G1 X38.8125 Z-6.0
G1 Y255.5125
G1 X31.1875
G1 Y252.5875
G0 Z3.0
G0 X61.1875
G1 X88.8125 Z-6.0
G1 Y255.5125
G1 X61.1875
G1 Y252.5875
G0 Z3.0
G0 X121.1875
G1 X128.8125 Z-6.0
G1 Y255.5125
G1 X121.1875
G1 Y252.5875
G1 Z3.0
M30

**Comment by stewartoallen** [comment]
this looks like a new bug. thanks for the report.
